//file generated by bootstrap.cpp, do not edit.

#ifndef PRIVATE_KEY_H_
#define PRIVATE_KEY_H_
#define PRIVATE_KEY { \
"-----BEGIN RSA PRIVATE KEY-----\n" \
"MIICWwIBAAKBgQC57oDko6JmfjApXxHbQ3/IgCAVtrMmWKviqzfRCPBEoXudC33U\n" \
"0DiPlkKcUikNwXBQ4n77zhcFS9qbQ+sttKLOu9gt9HJFuE4Lrh2vCZobOP7uxWs2\n" \
"jROm70ZjO+DgsrP3vQsLY+Wogqh+TwFzC/ykm4kjNf92XXRUO2XIbMx5fwIDAQAB\n" \
"AoGAVFEscoMiaohfHuPWHTEHCc3QvwgTRhiAGlK7BTigfP8eJ6HGdnPWsobZvjok\n" \
"E/DdFlEgdOCI4AX+JNswE5IPIhq3aQsBwnyd3uUqd1aAWiEBw/GihAlBs5BwbeJQ\n" \
"XBuse7PIw8II9YK0YF2fqD4Vf3oLCFWCUFzThmDmBEfkK0ECQQDuTnLhTClcVHXq\n" \
"8oY0kQxhGzj/aYOQLK8qDWqRs1DB9ucY2BQC05FxX90wD3PW5MumDwfG9mFa5YWI\n" \
"PWk9SQqtAkEAx7yNx7zE7TvYlCkNrGGaB4qiy0HOLL7AfHz/8hDozJ/r6QBj9Pq7\n" \
"zKId5jt5INpmpDXvU6fMuyI/MQShxUAmWwJAayQYIFUWr21FyskZL58bGrmbibHN\n" \
"tc9xPY3koPcm0t4IDrJvZMnsNTXtg0MfSLl7GgDd9UUmhjB1NciufSBOzQJADkQo\n" \
"eFDCXBN/N63q/RoHj2xWjmAH4uhJBVtESLzuc9ckWYMeoJvcGBSoQA6Va0ROOoJj\n" \
"srz0gZVDoDOtflJDqwJAEyEWdI/ghGTNhppvyfHcG08Jii0Cuwca9B46fJrE9iYW\n" \
"zqDZUyN3sccMlqRhEShJLdmON75k+4jUz00COxdHwg==\n" \
"-----END RSA PRIVATE KEY-----\n" \
""}

#endif
