//file generated by bootstrap.cpp, do not edit.

#ifndef PUBLIC_KEY_H_
#define PUBLIC_KEY_H_
#define PUBLIC_KEY { \
"-----BEGIN RSA PUBLIC KEY-----\n" \
"MIGJAoGBALnugOSjomZ+MClfEdtDf8iAIBW2syZYq+KrN9EI8EShe50LfdTQOI+W\n" \
"QpxSKQ3BcFDifvvOFwVL2ptD6y20os672C30ckW4TguuHa8Jmhs4/u7FazaNE6bv\n" \
"RmM74OCys/e9Cwtj5aiCqH5PAXML/KSbiSM1/3ZddFQ7ZchszHl/AgMBAAE=\n" \
"-----END RSA PUBLIC KEY-----\n" \
""}

#define SHARED_RANDOM 383;
#endif
